/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader, GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

type GLTFResult = GLTF & {
  nodes: {
    mergedBlocks: THREE.Mesh;
  };
  materials: {
    _defaultMat: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useLoader<GLTFResult>(
    GLTFLoader,
    '/HumanWorker.gltf'
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials._defaultMat}
        geometry={nodes.mergedBlocks.geometry}
      />
    </group>
  );
}
